@baseUrl = http://localhost:3000

### Create a company
POST {{baseUrl}}/authCompany/register-company
Content-Type: application/json

{
  "name": "steam",
  "email": "contact@steam.com",
  "password": "password",
  "template": [
    1, 2, 3, 4
  ]
}

### Login
POST {{baseUrl}}/authCompany/login-company
Content-Type: application/json

{
  "email": "contact@steam.com",
  "password": "password"
}

### Verify
POST {{baseUrl}}/authCompany/verify-company
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbnRhY3RAc3RlYW0uY29tIiwiaWF0IjoxNzMzMjM5NjEyLCJleHAiOjE4MTk2Mzk2MTJ9._ztgiXC3EDQjVawVr8S8S0wKYI9be60hn3rEnpcb7xw"
}
