@baseUrl = http://localhost:3000

### Get All groupIssues
GET {{baseUrl}}/groupIssue
Content-Type: application/json

### Create One groupIssue
POST {{baseUrl}}/groupIssue/create-groupIssue
Content-Type: application/json

{
    "groupIssueName": "New groupIssue Name"
}

### Delete issue by Name
DELETE {{baseUrl}}/groupIssue/delete-groupIssue
Content-Type: application/json

{
    "groupIssueName": "New groupIssue Name"
}

### Update issue Name
PATCH {{baseUrl}}/groupIssue/patch-groupIssueName
Content-Type: application/json

{
    "groupIssueName": "New groupIssue Name",
    "newGroupIssueName": "New GroupIssue Name"
}

