@baseUrl = http://localhost:3000

### Get All issues
GET {{baseUrl}}/issue
Content-Type: application/json

### Create One issue
POST {{baseUrl}}/issue/create-issue
Content-Type: application/json

{
    "issueName": "bbbb",
    "issueGroupName": "Gouvernance"
}

### Delete issue by Name
DELETE {{baseUrl}}/issue/delete-issue
Content-Type: application/json

{
    "issueName": "Energie2"
}

### Update issue Name
PATCH {{baseUrl}}/issue/patch-issueName
Content-Type: application/json

{
    "issueName": "New issue Name",
    "newIssueName": "New Issue Name"
}
