@baseUrl = http://localhost:3000

### Get All issues
GET {{baseUrl}}/issue
Content-Type: application/json

### Create One issue
POST {{baseUrl}}/issue/create-issue
Content-Type: application/json

{
    "issueName": "New issue Name"
}
