@baseUrl = http://localhost:3000

### Get All Templates
GET {{baseUrl}}/template
Content-Type: application/json

### Create One Template
POST {{baseUrl}}/template/create-template
Content-Type: application/json

{
    "templateName": "NewTemplateName"
}

### Create two Template
POST {{baseUrl}}/template/create-template
Content-Type: application/json

{
    "templateName": "NewTemplateName2"
}

### Delete Template by Name
DELETE {{baseUrl}}/template/delete-template
Content-Type: application/json

{
    "templateName": "NewTemplateName"
}

### Update Template Name
PATCH {{baseUrl}}/template/Patch-templateName
Content-Type: application/json

{
    "templateName": "NewTemplateName2",
    "newTemplateName": "NewTemplateName3"
}